version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'America/Lima'
      WEBPASSWORD: ${WEBPASSWORD}
    volumes:
      - '/run/media/sebas/Passport/config-docker/pihole/etc-pihole/:/etc/pihole/'
      - '/run/media/sebas/Passport/config-docker/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  plex:
    image: ghcr.io/linuxserver/plex:arm64v8-latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /run/media/sebas/Passport/config-docker/plex:/config
      - /run/media/sebas/Passport/media/series:/tv
      - /run/media/sebas/Passport/media/movies:/movies
    restart: unless-stopped

  
