version: "3"

services:
  radarr:
    image: lscr.io/linuxserver/radarr:arm64v8-latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Lima
    volumes:
      - /media/pi/Passport/config-docker/radarr:/config
      - /media/pi/Passport/media/movies:/movies
      - /media/pi/Passport/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Lima
    volumes:
      - /media/pi/Passport/config-docker/sonarr:/config
      - /media/pi/Passport/media/series:/tv #optional
      - /media/pi/Passport/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Lima
      - AUTO_UPDATE=true #optional
    volumes:
      - /media/pi/Passport/config-docker/jackett:/config
      - /media/pi/Passport/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:arm64v8-latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Lima
      - USER=sebasvr
      - PASS=${WEBPASSWORD}
    volumes:
      - /media/pi/Passport/config-docker/transmission:/config
      - /media/pi/Passport/downloads:/downloads
      - /media/pi/Passport/torrents:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

