version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    environment:
      TZ: 'America/Lima'
      WEBPASSWORD: ${WEBPASSWORD}
    volumes:
      - '/media/pi/Passport/config-docker/pihole/etc-pihole/:/etc/pihole/'
      - '/media/pi/Passport/config-docker/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  samba:
    container_name: samba
    image: dperson/samba:aarch64
    ports:
      - "139:139"
      - "445:445"
    environment:
      TZ: 'America/Lima'
    volumes:
      - '/media/pi/Passport/media:/mount/Passport/media'
      - '/media/pi/Passport/Universal:/mount/Passport/Universal'
    command: ['-u', 'sebas;${WEBPASSWORD}', '-s', 'users;/srv;no;no;no;sebas', '-s', 'Media;/mount/Passport/media;yes;no;no;sebas;sebas', '-s', 'Universal;/mount/Passport/Universal;yes;no;no;sebas;sebas']
    restart: unless-stopped

  plex:
    image: ghcr.io/linuxserver/plex:arm64v8-latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - /media/pi/Passport/config-docker/plex:/config
      - /media/pi/Passport/media/series:/tv
      - /media/pi/Passport/media/movies:/movies
      - /media/pi/Passport/media/music:/music
    restart: unless-stopped

  duplicati:
    image: lscr.io/linuxserver/duplicati:arm64v8-latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Lima
      # - CLI_ARGS= #optional
    volumes:
      - /media/pi/Passport/config-docker/duplicati:/config
      - /media/pi/Passport/Backups:/backups
      - /media/pi/Passport/Universal:/source
    ports:
      - 8200:8200
    restart: unless-stopped

